version: "3.9"
services:
  etlservice:
    build: 
      context: etlservice
    ports:
      - "8000:8000" 
  
  sensorsmock:
    build:
      context: sensors
    ports:
      - "3000:3000"
    environment:
      - SMART_THERMO_BUCKET=alybuckett
      - MOISTURE_MATE_URL=http://etlservice:8000/api/moisturemate
      - CARBON_SENSE_URL=http://etlservice:8000/api/carbonsense
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
